# Generated by Django 6.0.3 on 2026-03-04 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('nome_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('INVESTIMENTO', 'Conta Investimento/Corretora'), ('POUPANCA', 'Poupança')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_operacao', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('D', 'Dividendo/JCP')], max_length=1)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ativo')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='investimentos.conta')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Depósito)'), ('S', 'Saída (Saque/Pagamento)')], max_length=1)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.conta')),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investimentos.tipoativo'),
        ),
    ]
