# Generated by Django 6.0.3 on 2026-03-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoconta',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.conta'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='tipo_operacao',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('D', 'Dividendo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transf_recebidas', to='investimentos.conta')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transf_enviadas', to='investimentos.conta')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo', to='investimentos.conta')),
                ('origem_lanc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.lancamento')),
                ('origem_mov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.movimentacaoconta')),
                ('origem_transf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investimentos.transferencia')),
            ],
            options={
                'ordering': ['data', 'id'],
            },
        ),
    ]
